apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: {{ .Values.nifi.clusterName }}
spec:
  service:
    headlessEnabled: true
    labels:
      cluster-name: {{ .Values.nifi.clusterName }}
  {{- if .Values.nifi.ingress.enabled }}
  zkAddress: "zookeeper.zookeeper:2181"
  zkPath: /{{ .Values.nifi.clusterName }}
  externalServices:
    - metadata:
        labels:
          cluster-name: driver-{{ .Values.nifi.clusterName }}
      name: driver-ip
      spec:
        portConfigs:
          - internalListenerName: http
            port: 8080
        type: LoadBalancer
  {{- end }}
  clusterImage: {{ .Values.nifi.clusterImage }}
  initContainerImage: "bash:5.2.2"
  oneNifiNodePerNode: true
  readOnlyConfig:
    nifiProperties:
      overrideConfigs: |
        nifi.sensitive.props.key=thisIsABadSensitiveKeyPassword
  pod:
    labels:
      cluster-name: {{ .Values.nifi.clusterName }}
  nodeConfigGroups:
    default_group:
      imagePullPolicy: IfNotPresent
      isNode: true
      serviceAccountName: default
      storageConfigs:
        {{- range .Values.nifi.storageConfigs }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
            reclaimPolicy: Delete
            pvcSpec:
              accessModes:
                - ReadWriteOnce
              storageClassName: {{ .storageClassName }}
              resources:
                requests:
                  storage: {{ .storage }}
        {{- end }}
      {{- with .Values.nifi.resourcesRequirements }}
      resourcesRequirements:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  nodes:
    - id: 1
      nodeConfigGroup: "default_group"
    - id: 2
      nodeConfigGroup: "default_group"
  propagateLabels: true
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  listenersConfig:
    internalListeners:
      - containerPort: 8080
        type: http
        name: http
      - containerPort: 6007
        type: cluster
        name: cluster
      - containerPort: 10000
        type: s2s
        name: s2s
      - containerPort: 9090
        type: prometheus
        name: prometheus
      - containerPort: 6342
        type: load-balance
        name: load-balance
