{
 "title": "NiFi",
 "description": "A complete dashboard for all metrics exposed using PrometheusReportingTask",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "format": "s",
     "valueName": "current",
     "targets": [
      { "expr": "nifi_jvm_uptime" }
     ]
    },
    {
     "title": "JVM Heap Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_heap_usage", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Heap Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_heap_used", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Deamon Thread Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_daemon_thread_count", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Heap Non Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_heap_non_usage", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_gc_time", "legendFormat": "{{gc_name}}" }
     ]
    },
    {
     "title": "JVM GC Runs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_gc_runs", "legendFormat": " {{gc_name}}" }
     ]
    },
    {
     "title": "JVM File Descriptor Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_file_descriptor_usage", "legendFormat": " " }
     ]
    },
    {
     "title": "JVM Thread Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "nifi_jvm_thread_count", "legendFormat": " " }
     ]
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Lineage Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_average_lineage_duration",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Terminated Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_threads_terminated",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_threads_active",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FlowFiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_received",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    },
    {
     "title": "Transferred FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_transferred",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Sent FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_sent",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    },
    {
     "title": "Removed FlowFiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_flowfiles_removed",
       "legendFormat": "{{component_type}}  {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_input",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Output Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_output",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    },
    {
     "title": "Queued Items",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_items_queued",
       "legendFormat": "{{component_type}} {{component_name}} {{component_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Contents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Input Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "mbytes", "label": "In MiB" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_input_total",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Total Output Content",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "mbytes", "label": "In MiB" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_output_total",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Total Queued Content",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "mbytes", "label": "In MiB" }
     ],
     "targets": [
      {
       "expr": "nifi_size_content_queued_total",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backpressure Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_bytes_threshold",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    },
    {
     "title": "Backpressure Objects",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_object_threshold",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    },
    {
     "title": "Backpressure Enabled",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_backpressure_enabled",
       "legendFormat": "{{component_type}} {{component_name}} {{source_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transferred Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_transferred",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Received Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_received",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Written Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_written",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Sent Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_sent",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    },
    {
     "title": "Read Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nifi_amount_bytes_read",
       "legendFormat": "{{component_type}} {{component_name}}"
      }
     ]
    }
   ]
  }
 ]
}